# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccd4898bc14936e759e2fda203c23d47fc4f5d4e01bd810a649e26576d09602723d22db2f36c2e82c8f6745903bdb670471adec96d35208a4d924dc8d62f5c7e

test:
  secret_key_base: a4dfd770c60110aa3208efb0cf7ac2060e42f937a34e006c69d90175abaef9a5dc430caad9cde6c4bc54bae00c923c8d2220777cb2dda17398a8108b22843448

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
